21-authentication/snack-tracker/config/routes.rb
Rails.application.routes.draw do

    resources :snacks
    resources :retailers, only: [:show, :index, :new, :create, :destroy]
    resources :users, only: [:new, :create]
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: "sessions#destroy"

end

21-authentication/snack-tracker/app/models/retailer.rb
class Retailer < ApplicationRecord
    has_many :snacks
    accepts_nested_attributes_for :snacks, reject_if: proc {|params| params[:name].blank?}

    validates :name, uniqueness: true, presence: true
    validates :year_established, presence: true
    validate :year_established_must_be_valid, 
        unless: Proc.new {|attribute| attribute.year_established.blank? }

    def year_established_must_be_valid
        if !(self.year_established > 1800 && self.year_established <= Date.today.year)
            errors.add(:year_established, "must be between 1800 and #{Date.today.year}")
        end
    end 
end

21-authentication/snack-tracker/app/models/snack.rb
class Snack < ApplicationRecord
    belongs_to :retailer, optional: true

    validates :name, presence: true, uniqueness: true
    validates :calories, presence: true
    validates :deliciousness, presence: true
    
end

21-authentication/snack-tracker/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

21-authentication/snack-tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_username

    # memoization
    def current_username
        if @current_user
            @current_user.username
        else
            @current_user = User.find_by(id: session[:user_id])
            @current_user.username
        end
    end
end

21-authentication/snack-tracker/app/controllers/retailers_controller.rb
class RetailersController < ApplicationController

  def index
    @retailers = Retailer.all
  end

  def show
    @retailer = Retailer.find(params[:id])
  end

  def new
    @retailer = Retailer.new
    @retailer.snacks.build 
  end

  def create
    @retailer = Retailer.create(accepted_retailer_form_fields)
    if @retailer.errors
      render :new
    else
      redirect_to retailer_path(@retailer)
    end
  end

  def destroy
    @retailer = Retailer.find(params[:id])
    @retailer.destroy
    redirect_to retailers_path
  end

  private

  def accepted_retailer_form_fields
    params.require(:retailer).permit(:name, :year_established,
        snacks_attributes: [:name, :calories, :deliciousness])
  end
end

21-authentication/snack-tracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:username])


    if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id  # login 
        redirect_to snacks_path
    else 
        flash.notice = "Username and Password do not match"
        render :new
    end
  end

  def destroy # logout
    session[:user_id] = nil
    redirect_to login_path
  end

end

21-authentication/snack-tracker/app/controllers/snacks_controller.rb
require 'pry'
class SnacksController < ApplicationController

  before_action :find_snack, only: [:edit, :show, :update, :destroy]

  def index
    @snacks = Snack.all
  end
  
  def show
    cookies["favorite"] = "chocolate-chip"
    # cookies = {"favorite": "chocolate-chip"}
    session["secret-favorite"] = "oatmeal raisin"
  end

  def new
    # loads empty create form
    @snack = Snack.new
  end

  def create
    # byebug
    @snack = Snack.create(accepted_params)
    if @snack.errors

  
      render :new
    else
      redirect_to snack_path(@snack)
    end
  end

  def edit
  end

  def update
    @snack.update(accepted_params)
    redirect_to snack_path(@snack)
  end

  def destroy
    @snack.destroy
    redirect_to snacks_path
  end

  private

  def accepted_params
    params.require(:snack).permit(:name, :deliciousness, :calories)
  end

  def find_snack
    @snack = Snack.find(params[:id])
  end
end

21-authentication/snack-tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.valid?
        @user.save
        session[:user_id] = @user.id 
        redirect_to snacks_path
    else 
        render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:username,
        :password, :password_confirmation)
  end

end

21-authentication/snack-tracker/app/helpers/retailers_helper.rb
module RetailersHelper
end

21-authentication/snack-tracker/app/helpers/sessions_helper.rb
module SessionsHelper
end

21-authentication/snack-tracker/app/helpers/snacks_helper.rb
module SnacksHelper
end

21-authentication/snack-tracker/app/helpers/users_helper.rb
module UsersHelper
end

21-authentication/snack-tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnackTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <% if current_username %>
          <h4>Hi <%= current_username %>.  You are awesome</h4>
          <h5><%= link_to "Logout", logout_path, method: "DELETE" %></h5>
      <% else %>
          <h5><%= link_to "Login", login_path %></h5>
      <% end %>
    </div>
    <%= yield %>

  </body>
</html>

21-authentication/snack-tracker/app/views/retailers/index.html.erb
<h1>Retailers#index</h1>
<p>Find me in app/views/retailers/index.html.erb</p>

<h2>Do cookies exist here?  I like <%= cookies["favorite"] %> and <%= session["secret-favorite"] %>
<ul>
    <% @retailers.each do |r| %>
        <li><%= link_to r.name, retailer_path(r) %></li>
    <% end %>
</ul>

21-authentication/snack-tracker/app/views/retailers/new.html.erb
<h1>New Retailer</h1>

<%= render partial: "shared/error_list", locals: {new_object: @retailer} %>

<%= form_for @retailer do |r| %>
    <%= r.label :name %>
    <%= r.text_field :name %>
    <%= r.label :year_established %>
    <%= r.number_field :year_established %>

    <h2>Snacks</h2>
    <%= r.fields_for :snacks do |snack| %>
        <%= snack.label :name %>
        <%= snack.text_field :name %>
        <%= snack.label :calories %>
        <%= snack.number_field :calories %>
        <%= snack.label :deliciousness %>
        <%= snack.number_field :deliciousness %>
    <% end %>

    <%= r.submit "Create Retailer" %>

<% end %>

21-authentication/snack-tracker/app/views/retailers/show.html.erb
<h1><%= @retailer.name %></h1>

<p>Year established: <%= @retailer.year_established %></p>

<ul>
    <% @retailer.snacks.each do |snack| %>
        <li><%= link_to snack.name, snack_path(snack) %></li>
    <% end %>
</ul>

<%= link_to "Retailer Index Page", retailers_path %>

<h4>Delete by form</h4>
<%= form_tag @retailer, method: "DELETE" do %>
    <%= submit_tag "DESTROY THIS RETAILER" %>
<% end %>

<h4>Delete by link</h4>
<%= link_to "Delete this retailer by a link",
    retailer_path(@retailer),
    {method: :delete, class: "looks_like_a_button"} %>

21-authentication/snack-tracker/app/views/shared/_error_list.html.erb
<% if new_object.errors %>
    <ul class="error_list">
        <% new_object.errors.full_messages.each do |error| %>
            <li><%= error %></li>
        <% end %>
    </ul>
<% end %>

21-authentication/snack-tracker/app/views/snacks/_snack_form.html.erb
<%= render partial: "shared/error_list", locals: {new_object: @snack} %>

<%= form_for @snack do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :calories %>
    <%= f.number_field :calories %>
    <%= f.label :deliciousness %>
    <%= f.select :deliciousness, (1..10) %>
    <%= f.submit "Snackify" %>
<% end %>

21-authentication/snack-tracker/app/views/snacks/edit.html.erb
<h1>Edit Snack</h1>

<%= render "snack_form" %>

<h3>Here's an edit form above</h3>

21-authentication/snack-tracker/app/views/snacks/index.html.erb
<h1>Snacks Index Page for <%= current_username %></h1>



<h2>My favorite cookie is: <%= cookies['favorite'] %></h2>

<h3>My secret favorite cookie is <%= session["secret-favorite"] %></h3>

<ul>
    <% @snacks.each do |s| %>
        <li><%= link_to s.name, snack_path(s) %></li>
    <% end %>
</ul>

21-authentication/snack-tracker/app/views/snacks/new.html.erb
<h1>New Snack</h1>

<%= render "snack_form" %>

21-authentication/snack-tracker/app/views/snacks/show.html.erb
<div class="snack-container">
    
<h1><%= @snack.name %></h1>

<h3>Deliciousness: <%= @snack.deliciousness %></h3>
<h4>Calories: <%= @snack.calories %></h4>

<% if @snack.retailer %>
    <h4><%= link_to @snack.retailer.name, retailer_path(@snack.retailer) %></h4>
<% end %> 

</div>
<%= link_to "Edit Snack", edit_snack_path(@snack) %>

<%= form_tag @snack, :class => 'delete-button', method: "DELETE" do %>
    <%= submit_tag "Delete" %>
<% end %>

<%= link_to "Snacks Index Page", snacks_path %>

21-authentication/snack-tracker/app/views/users/new.html.erb
<h1>Make a new user or <%= link_to "login", login_path %></h1>


<%= render partial: "shared/error_list", locals: {new_object: @user} %>

<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit %>
<% end %>